base/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
  path("", views.homePage, name="homePage"),
  path("user/<str:pk>/", views.userPage, name="userPage"),
  path("user-form/", views.userFormPage, name="userFormPage"),
  path("get-reg-key/", views.getRegKeyPage, name="getRegKeyPage"),
  path('login/', views.loginPage, name="login"),
  path('logout/', views.logoutUser, name="logout"),
  path('change-password/', views.changePassword, name="changePassword"),
  path('register/', views.registerPage, name="register"),
  path('send-otp/', views.sendOTP, name='sendOTP'),
  path('verify-otp', views.verifyOTP, name='verifyOTP'),
  path('reset-password/', views.MyPasswordResetView.as_view(extra_context={'page': 'page'}), name='reset_password'),
  path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(template_name='base/reset_password/success_message.html', extra_context={'page': 'page', 'linkSend':'linkSend'}), name='password_reset_done'),
  path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(template_name='base/reset_password_form.html', extra_context={'page': 'page'}), name='password_reset_confirm'),
  path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='base/reset_password/success_message.html', extra_context={'page': 'page'} ), name='password_reset_complete'),
]

dpi_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_delete
import os

GENDER_CHOICES = [
  ('Male', 'Male'),
  ('Female', 'Female'),
]

BLOOD_GROUP_CHOICES = [
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
]

JOB_CATEGORY_CHOICES = [
    ('Government', 'Government'),
    ('Private', 'Private'),
    ('Bussiness', 'Bussiness'),
    ('Homemaker', 'Homemaker'),
    ('Others', 'Others'),
]

DEPARTMENT_CHOICES = [
  ('Civil Eng.', 'Civil Eng.'),
  ('Architectural Eng.', 'Architectural Eng.'),
  ('Environmental Eng.', 'Environmental Eng.'),
  ('Mechanical Eng.', 'Mechanical Eng.'),
  ('Chemical Eng.', 'Chemical Eng.'),
  ('Food Eng.', 'Food Eng.'),
  ('Electrical Eng.', 'Electrical Eng.'),
  ('Electronics Eng.', 'Electronics Eng.'),
  ('Computer Eng.', 'Computer Eng.'),
  ('Power Eng.', 'Power Eng.'),
  ('Automobile Eng.', 'Automobile Eng.'),
  ('RAC Eng.', 'RAC Eng.'),
]
 
class User(AbstractUser):
  name = models.CharField(max_length=200, null=True)
  email = models.EmailField(unique=True)
  profile_bio = models.TextField(null=True)
  date_of_birth = models.DateField(null=True)
  updated = models.DateTimeField(auto_now=True, null=True)
  current_address = models.TextField(null=True, blank=True)
  permanent_address = models.TextField(null=True, blank=True)

  resume = models.FileField(upload_to='pdfs/', null=True, blank=True) # Stores PDF files in the 'pdfs/' subdirectory of MEDIA_ROOT

  gender = models.CharField(
    max_length=6,
    choices=GENDER_CHOICES,
    null=True,
  )
  blood_group = models.CharField(
      max_length=3,
      choices=BLOOD_GROUP_CHOICES,
      null=True,
  )

  department = models.CharField(
      max_length=18,
      choices=DEPARTMENT_CHOICES,
      null=True,
  )

  job_type = models.CharField(max_length=10, choices=JOB_CATEGORY_CHOICES, null=True, blank=True)
  job_role = models.CharField(max_length=100, null=True, blank=True)
  job_description = models.TextField(null=True, blank=True)


  avatar = models.ImageField(upload_to='images/', null=True, blank=True)

  # to use user.date_joined;

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = []

  def __str__(self):
    return self.email

  def has_complete_profile(self):
    return self.name and self.profile_bio and self.date_of_birth and self.gender and self.blood_group



class ContactInfo(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="contacts")
  type = models.CharField(max_length=50)
  value = models.CharField(max_length=255)

  def __str__(self):
    return f"{self.type}: {self.value}"
  

class Registration(models.Model):
  email = models.EmailField(null=True)
  otp = models.CharField(max_length=6, null=True)
  created_at = models.DateTimeField(auto_now=True)
  registrationKey = models.CharField(max_length=8)
  is_used = models.BooleanField(default=False)

  def __str__(self):
    return f"{self.email} - {self.otp}"
    




@receiver(pre_save, sender=User)
def auto_delete_file_on_change(sender, instance, **kwargs):
    if not instance.pk:
        return  # New object, no old file to delete

    try:
        old_instance = User.objects.get(pk=instance.pk)
    except User.DoesNotExist:
        return

    # Check image change
    if old_instance.avatar and old_instance.avatar != instance.avatar:
        if os.path.isfile(old_instance.avatar.path):
            os.remove(old_instance.avatar.path)

    # Check resume change
    if old_instance.resume and old_instance.resume != instance.resume:
        if os.path.isfile(old_instance.resume.path):
            os.remove(old_instance.resume.path)


# 🔹 Delete files when object is deleted
@receiver(post_delete, sender=User)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.avatar and os.path.isfile(instance.avatar.path):
        os.remove(instance.avatar.path)

    if instance.resume and os.path.isfile(instance.resume.path):
        os.remove(instance.resume.path)

base/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from .models import User, Registration
from .forms import MyUserCreationForm, UserInfoForm, EmailForm
from django.contrib.auth.forms import PasswordChangeForm
import random
from django.core.mail import send_mail
from datetime import  timedelta
from django.utils import timezone
from django.db.models import Q
from .util import validateContacts, getContactErrorMessage, getUserFormErrorMessage, getUserCreationFormErrorMessage, getUserAge, getUserContacts, getContactAndSocialMediaHTMLText, getSearchedUser, getHomePageContextDict, saveProfilePhotoAndResume, getEncryptedValue, getRegistrationKeys
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string


@login_required(login_url='login')
def homePage(request):
  users = None
  method = ''
  if request.method == "POST":
    filter_kwargs = getSearchedUser(request.POST)
    if filter_kwargs:
      users = User.objects.filter(
        ~Q(profile_bio=None) &
        ~Q(id=request.user.id) &
        Q(**filter_kwargs)
      )
      method = 'POST'
  else:
    users = User.objects.filter(
      ~Q(profile_bio=None) &
      ~Q(id=request.user.id)
    )
    method = 'GET'
  context = getHomePageContextDict(users, method)
  return render(request, "base/home.html", context) 

@login_required(login_url='login')
def userPage(request, pk):
  user = User.objects.get(id=pk)
  age = getUserAge(user.date_of_birth)
  contacts = getUserContacts(user.contacts.all())
  context = {'user': user, "age": age, "contacts": contacts}
  return render(request, "base/user.html", context) 

# request.POST = {
#     'first_name': 'Kaushiq',
#     'age': '25',
#     'csrfmiddlewaretoken': 'XYZ123...'
# }
# This is the format of request object; as long as the name attribute matches the original model field name you can use any html element (i.e input, textarea, select whatever you want). If you use same name attribute for different element the last element name will be found using request.POST.get("name_attribut") but using getList() method you can get all the element value. This is what I did for contact_type[] and contact_value[] elements;
@login_required(login_url='login')
def userFormPage(request):
  context = {"header": "One More Step", "body": "Please complete your profile to continue."}
  if request.method == "POST":
    form = UserInfoForm(request.POST, request.FILES, instance=request.user)
    if form.is_valid():
      print("form valid")
      user = form.save(commit=False)
      saveProfilePhotoAndResume(user, request)
      contact_error = validateContacts(request.POST, user)
      if contact_error:
        context['body'] = getContactErrorMessage(form)
      else:
        return redirect('userPage', pk=user.id)
    else:
      context['body'] = getUserFormErrorMessage(form)
    context['header'] = 'Error'
  
  if request.user.has_complete_profile():
     user = request.user
     contactAndSocialMediaHTMLText = getContactAndSocialMediaHTMLText(user.contacts.all())
     context["user"] = user
     context['contactAndSocialMediaHTMLText'] = contactAndSocialMediaHTMLText
  else:
     context['user'] = "user"
     context['userFormPage'] = "userFormPage"
  return render(request, "base/user_form.html", context) 

def check_if_superuser(user):
    return user.is_superuser

@login_required(login_url='login')
@user_passes_test(check_if_superuser)
def getRegKeyPage(request):
  if request.method == "POST":
    value = int(request.POST.get("input-value"))
    registrationKeys = getRegistrationKeys(value)
    for registrationKey in registrationKeys:
      Registration.objects.create(
        registrationKey = registrationKey
      )
    return redirect("getRegKeyPage")
     
  registrationObjs = Registration.objects.filter(is_used=False) 
  context = {"registrationObjs": registrationObjs}
  return render(request, "base/get_reg_key.html", context) 

# need to modify these views

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('homePage')
    context = {'page': 'login'}
    if request.method == 'POST':
        email = request.POST.get('email').strip().lower()
        password = request.POST.get('password')
        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)
            if user is not None:
              login(request, user)
              return redirect('homePage')
        except:
            pass
        context['loginError'] = 'Invalid email or password.'
        context['email'] = email
        context['password'] = password
    else: 
       context['success'] = request.session.pop("register-success", None)
    return render(request, 'base/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
def changePassword(request):
   context = {'oldPassword': 'oldPassword'}
   if request.method == 'POST':
      form = PasswordChangeForm(request.user, request.POST)
      if form.is_valid():
          user = form.save()
          update_session_auth_hash(request, user)  # Important!
          messages.success(request, 'Your password was successfully updated!')
          return redirect('homePage')
      else:
          context["passwordResetError"] = getUserCreationFormErrorMessage(form)
   return render(request, 'base/reset_password_form.html', context)

def sendOTP(request):
  context = {'page': 'page'} # for not showing the navbar
  email = None
  registrationKey = None
  if request.method == 'POST':
    form = EmailForm(request.POST)
    if form.is_valid(): 
      email = form.cleaned_data['email']
      registrationKey = form.cleaned_data['registrationKey']
      try:
         user = User.objects.get(email=email)
         deleteRegKeyObj(registrationKey)
      except:
         try:
            registrationObj = Registration.objects.get(registrationKey=registrationKey)
            sendMail(registrationObj=registrationObj, email=email)
            request.session['regKeyObjId'] = registrationObj.id
            return redirect("verifyOTP")
         except:
            pass
    context['formError'] = "Invalid email or registration key."
  else:
     context['formError'] = request.session.pop('session_expired', None)
  context['email'] = email
  context['registrationKey'] = registrationKey
  return render(request, 'base/send_otp.html', context)

def verifyOTP(request):
  context = {'page': 'page'} # for not showing the navbar
  regKeyObjId = request.session.get('regKeyObjId')
  try:
     registrationObj = Registration.objects.get(id=regKeyObjId)
     timeLeft = get_remaining_seconds(registrationObj.created_at)
     if request.method == 'POST':
        if timeLeft == 0:
           sendMail(registrationObj=registrationObj, email=None)
           return redirect("verifyOTP")
        else:
          if registrationObj.otp == request.POST.get("otp"):
              registrationObj.save()
              return redirect('register')
          context['otp_error'] = "Invalid otp, try again."
     context['timeLeft'] = timeLeft
     return render(request, 'base/verify_otp.html', context)
  except:
     request.session['session_expired'] = "Your session has been expired, please try again."
     return redirect('sendOTP')

def registerPage(request):
  context = {'page': 'register'} # for not showing the navbar
  regKeyObjId = request.session.get('regKeyObjId')
  try:
      registrationObj = Registration.objects.get(id=regKeyObjId)
      if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = registrationObj.email
            user.save()
            registrationObj.delete()
            request.session.pop('regKeyObjId', None)
            request.session['register-success'] = "Your account has been created successfully, you can now login."
            return redirect('login')
        else:
           context['registrationError'] = getUserCreationFormErrorMessage(form)
      context['email'] = registrationObj.email
      print(request.method)
      return render(request, 'base/login_register.html', context)
  except:
      request.session['session_expired'] = "Your session has been expired, please try again."
      return redirect('sendOTP')

def get_remaining_seconds(start_time):
    end_time = start_time + timedelta(seconds=120)
    now = timezone.now()
    remaining = (end_time - now).total_seconds()
    return max(0, int(remaining))

def sendMail(registrationObj, email):
    if email:
       registrationObj.email = email
    else:
       email = registrationObj.email
    otp = str(random.randint(100000, 999999))
    registrationObj.otp = otp
    send_mail(
      'Verify your email',
      f'Your verification code is: {otp}',
      'no-reply@yourdomain.com',
      [email],
      fail_silently=False,
    )
    registrationObj.is_used = True
    registrationObj.save()


def deleteRegKeyObj(registrationKey):
    try:
      registrationObj = Registration.objects.get(registrationKey=registrationKey)
      registrationObj.delete()
    except:
      pass

class MyPasswordResetView(PasswordResetView):
    template_name = 'base/reset_password/send_link.html'
    subject_template_name = 'base/reset_password/email_subject.txt'
    email_template_name = 'base/reset_password/email_body.txt'

base/templates/base/get_reg_key.html
{% extends "main.html" %}

{% block content %}

{% if registrationObjs %}

<div class="grid-container navbar-exist">
    <div class="grid-wrapper">
      <h1>Available Registration Keys</h1>
      <div id="grid" class="grid reg-key-grid" >
        {% for registrationObj in registrationObjs %}
          <div class="cell">{{ registrationObj.registrationKey }}</div>
        {% endfor %}
      </div>
    </div>
  </div>

{% else %}
  <div class="container navbar-exist">
    <div class="wrapper">
        <h2>Generate Key</h2>
        <form class="form" action="" method="POST">
          {% csrf_token %}
            <div class="field__group">
              <input class="input-field" type="text" autofocus name="input-value" placeholder=" " required pattern="[0-9]*" inputmode="numeric" oninput="this.value = this.value.replace(/[^0-9]/g, '');">
              <label class="input-label" for="registration-key">Number of Keys</label>
            </div>  
            <div class="submit-button-margin">
                <button type="submit" class="btn btn--main">
                    Generate
                </button>
            </div>
            
        </form>      
    </div>
  </div>

{% endif %}
  
{% endblock content %}

base/templates/base/home.html
{% extends "main.html" %}
{% load static %}

{% block content %}
<div class="grid-container navbar-exist">
  <div class="grid-wrapper">
    <div class="grid profile-card-grid">
      {% if users %}
            {% for user in users %}
              <a href="{% url 'userPage' user.id %}">
                  <div class="cell profile-card">
                    <div class="profile-photo">
                      {% if user.avatar %}
                          <img src="{{user.avatar.url}}" alt="" />
                      {% else %}
                          <img src="{% static 'icons/avatar.svg' %}" alt="" />
                      {% endif %}
                    </div>
                    <div class="name">{{user.name|truncatewords:3}}</div>
                    <div class="job">{{user.profile_bio|truncatewords:5}}</div>
                  </div>	
              </a>
            {% endfor %}
      {% else %}
           {% if method == 'POST' %}   
              <a href="{% url 'homePage' %}" class="no-user-home-page-button">Home Page</a>
           {% else %}
              <a href="{% url 'userPage' user.id %}" class="no-user-home-page-button">My Profile</a>
           {% endif %}
      {% endif %}

    </div>
  </div>
</div>

{% endblock content %}

base/templates/base/login_register.html
{% extends "main.html" %}

{% block content %}

{% if page == "login" %}

  <div class="container">
    {% if success %}
    <div class="password-criteria green-border-background">
      <p>{{success}}</p>
    </div>
    {% endif %}

    {% if loginError %}
        <div class="password-criteria text-align-center red-border-background">
          <p>{{ loginError }}</p>
        </div>
    {% endif %}

    <div class="wrapper">
        <h2>Log In</h2>
        <form class="form" action="" method="POST">

          {% csrf_token %}
          
            <div class="field__group">
              <input autofocus class="input-field" id="email" type="email" name="email" {% if email %} value="{{email}}" {% endif %} placeholder=" " autocomplete="off" required>
              <label class="input-label" for="email">Email</label>
            </div>
  
            <div class="field__group">
              <input class="input-field" id="password" name="password" type="password" {% if password %} value="{{password}}" {% endif %} autocomplete="new-password" placeholder=" " required>
              <label class="input-label" for="password">Password</label>
            </div>
            <a href="{% url 'reset_password' %}" style="margin-top: .25rem;" class="btn btn--link">Forgot password?</a>

            <div class="submit-button-margin">
              <button class="btn btn--main">
                <svg fill="white" version="1.1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 32 32">
                  <title>login</title>
                  <path d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"></path>
                  <path d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"></path>
                </svg>
                Login
              </button>
            </div>
            
        </form>
        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'sendOTP' %}" class="btn btn--link">Register</a>
        </div>
      
    </div>
  </div> 
    

{% elif page == "register" %}
    <div class="container">

      {% if registrationError %}
          <div class="password-criteria red-border-background">
            <p>{{ registrationError }}</p>
          </div>
      {% endif %}


      <div class="password-criteria green-border-background">
        <p>Password Criteria:</p>
        <p>1. Your password can’t be too similar to your other personal information.</p>
        <p>2. Your password must contain at least 8 characters.</p>
        <p>3. Your password can’t be a commonly used password.</p>
        <p>4. Your password can’t be entirely numeric.</p>
      </div>
      <div class="wrapper">
          <h2>Register</h2>
          <form class="form" action="" method="POST">
              {% csrf_token %}

              <div class="field__group">
                
                <input class="input-field" type="email" name="email" maxlength="254" {% if email %} value="{{email}}" {% endif %} placeholder=" " autofocus autocomplete="off" required id="id_email">
                <label class="input-label" for="id_email">Email</label>
              </div>

              <div class="field__group">
                
                <input class="input-field" type="password" name="password1" placeholder=" " autocomplete="new-password" required id="id_password1">   
                <label class="input-label" for="id_password1">Password</label>            
              </div>
              
              <div class="field__group">
                <input class="input-field" type="password" name="password2" autocomplete="new-password" placeholder=" " required id="id_password2">
                <label class="input-label" for="id_password2">Password confirmation</label>
              </div>

              <div class="submit-button-margin">
                  <button class="btn btn--main" type="submit">
                    <svg fill="white" version="1.1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 32 32">
                      <title>lock</title>
                      <path
                        d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
                      </path>
                      <path
                        d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
                      </path>
                    </svg>

                    Register
                </button>
              </div>
              
            
          </form>        
      </div>
    </div> 
{% endif %}
  
{% endblock content %}

base/templates/base/reset_password_form.html
{% extends "main.html" %}

{% block content %}

<div class="container {% if oldPassword %} navbar-exist {% endif %} ">
        {% if passwordResetError %}
            <div class="password-criteria red-border-background">
              <p>Password Error:</p>
              <p>{{ passwordResetError }}</p>
            </div>
        {% endif %}

        <div class="password-criteria green-border-background">
          <p>Password Criteria:</p>
          <p>1. Your password can’t be too similar to your other personal information.</p>
          <p>2. Your password must contain at least 8 characters.</p>
          <p>3. Your password can’t be a commonly used password.</p>
          <p>4. Your password can’t be entirely numeric.</p>
        </div>


    <div class="wrapper">
        <h2>{% if oldPassword %} Change {% else %} Reset {% endif %} Password</h2>
        <form class="form" action="" method="POST">

          {% csrf_token %}
            {% if oldPassword %}
              <div class="field__group">
                <input class="input-field" id="id_old_password" type="password" name="old_password" autofocus autocomplete="off"  placeholder=" " required>
                <label class="input-label" for="id_old_password">Old Password</label>
              </div>
            {% endif %}

            <div class="field__group">
              <input class="input-field" id="id_new_password1" type="password" autocomplete="new-password" name="new_password1"  placeholder=" " required>
              <label class="input-label" for="id_new_password1">New Password</label>
            </div>

            <div class="field__group">
              <input class="input-field" id="id_new_password2" type="password" autocomplete="new-password" name="new_password2"  placeholder=" " required>
              <label class="input-label" for="id_new_password2">New Password Confirmation</label>
            </div>
              
            <div class="submit-button-margin">
                <button type="submit" class="btn btn--main">
                  <svg fill="white" version="1.1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 32 32">
                    <title>Submit</title>
                    <path d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"></path>
                    <path d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"></path>
                  </svg>
                  Submit
                </button>
            </div>
            
        </form>
      
    </div>
  </div> 

{% endblock content %}

base/templates/base/send_otp.html
{% extends "main.html" %}

{% block content %}

<div class="container">
      {% if formError %}
          <div class="password-criteria text-align-center red-border-background">
            <p>{{ formError }}</p>
          </div>
      {% endif %}

      <div class="password-criteria text-align-center green-border-background">
        <p>Please contact your site admin for registration key.</p>
      </div>
    <div class="wrapper">
        <h2>Email Verification</h2>
        <form class="form" action="" method="POST">
            {% csrf_token %}
            <div class="field__group">
              <input autocomplete="off" class="input-field" autofocus id="email" {% if email %} value="{{email}}" {% endif %} type="email" name="email" placeholder=" " required>
              <label class="input-label" for="email">Email</label>
            </div>   

            <div class="field__group">
              <input autocomplete="off" class="input-field" id="registration-key" {% if registrationKey %} value="{{registrationKey}}" {% endif %}  type="text" name="registrationKey" placeholder=" " required>
              <label class="input-label" for="registration-key">Registration Key</label>
            </div> 
            
            <div class="submit-button-margin">
              <button type="submit" class="btn btn--main">
                Send OTP
              </button>   
            </div>
                       
        </form>      
    </div>
</div> 

{% endblock content %}

base/templates/base/verify_otp.html
{% extends "main.html" %}

{% block content %}

<div class="container">
    <div id="otp-time-container">
      <div class="password-criteria green-border-background">
            <p>An OTP has been sent to your email. Please submit the OTP in <span class="error" id="otp-timer"></span> minutes.</p>
      </div>
    </div>
    
    <div class="wrapper">
        <h2>OTP Verification</h2>
        <form class="form" action="" method="POST">
            {% csrf_token %}
            <div class="field__group">
              <input autocomplete="off" class="input-field" id="otp" type="text" name="otp" placeholder=" " required>
              <label class="input-label" for="otp">OTP</label>
            </div>    
            {% if otpError %} <div class="error">{{otpError}}</div> {% endif %}
            <input autocomplete="off" id="time-left-input" type="hidden" {% if timeLeft %} value="{{timeLeft}}" {% endif %}/>    
            <div class="submit-button-margin">
              <button id="submit-resend-otp-button" type="submit" class="btn btn--main">
                Submit OTP
              </button>
            </div>
        </form>      
    </div>
  </div> 

{% endblock content %}